package br.com.rendmais.common.enums;

public enum MessageType {
    HANDSHAKE,
    HANDSHAKE_RESPONSE,
    HEARTBEAT,
    HEARTBEAT_RESPONSE,
    TASK_REQUEST,
    TASK_RESULT,
    PEER_ADVERTISEMENT,
    PEER_DISCOVERY,
    CONNECTION_CLOSE,
    ERROR,
    
    // Passive Income Data Collection Messages
    DATA_COLLECTION_TASK_REQUEST,
    DATA_COLLECTION_TASK_RESPONSE,
    DATA_COLLECTION_TASK_RESULT,
    DATA_COLLECTION_TASK_PROGRESS,
    DATA_COLLECTION_PEER_ADVERTISEMENT,
    DATA_COLLECTION_PEER_DISCOVERY,
    DATA_COLLECTION_RESOURCE_UPDATE
}
